//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientele2
    {
        public int ID { get; set; }
        public string ClientCode { get; set; }
        public string MembershipEntry { get; set; }
        public Nullable<System.DateTime> PreOrientationDate { get; set; }
        public string MembershipOrientationConductedby { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string SSS { get; set; }
        public string TIN { get; set; }
        public string Shift { get; set; }
        public string DepartmentOrArea { get; set; }
        public string LocalNo { get; set; }
        public string Degree { get; set; }
        public string SpouseContactNo { get; set; }
        public Nullable<System.DateTime> SpouseBirthday { get; set; }
        public string SpouseEducationalAttaintment { get; set; }
        public string SpouseDegree { get; set; }
        public string SpouseEmployer { get; set; }
        public string SpouseOfficeAddress { get; set; }
        public string FatherName { get; set; }
        public string FatherOcc { get; set; }
        public Nullable<System.DateTime> FatherBirthday { get; set; }
        public string FatherOfficeAddress { get; set; }
        public string MotherName { get; set; }
        public string MotherOcc { get; set; }
        public Nullable<System.DateTime> MotherBirthday { get; set; }
        public string MembershipStatus { get; set; }
        public string EmployerName { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeZip { get; set; }
        public string OfficePhone { get; set; }
        public string OtherSourceOfIncome { get; set; }
        public Nullable<decimal> OtherSourceMonthlyIncome { get; set; }
    }
}
