//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientele
    {
        public string ClientCode { get; set; }
        public string CenterGrpKey { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateOfMembership { get; set; }
        public Nullable<short> ClientType { get; set; }
        public Nullable<short> ClientClass { get; set; }
        public Nullable<short> EmployeeType { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string TelNum { get; set; }
        public string PlBirth { get; set; }
        public Nullable<System.DateTime> DtBirth { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string SpouseName { get; set; }
        public Nullable<short> EduAtt { get; set; }
        public Nullable<short> CivStatus { get; set; }
        public Nullable<System.DateTime> DtOfTerminate { get; set; }
        public string UserRefCD { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public string SpouseOcc { get; set; }
        public Nullable<decimal> SpouseMonSal { get; set; }
        public Nullable<int> MemberType { get; set; }
        public string Occupation { get; set; }
        public string Office { get; set; }
        public string Department { get; set; }
        public decimal MFee_amt { get; set; }
        public string BankAcctNo { get; set; }
        public string BankBranch { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public decimal MaxShareCapital { get; set; }
        public string EditClientCode { get; set; }
    }
}
