//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberPortal.Models
{
    using System;
    
    public partial class usp_CreateAmortization_Result1
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<decimal> Principal { get; set; }
        public Nullable<decimal> interest { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> Balances { get; set; }
    }
}
