//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidDay
    {
        public int ValidDaysID { get; set; }
        public short ValidDayMode { get; set; }
        public short ValidDay1 { get; set; }
        public short StartDay { get; set; }
        public short EndDay { get; set; }
    }
}
